verbosity = "Error"
native_grid_format = "su2"

[file_structure]
config = "config/config.toml"
solver = "config/solver"
discretisation = "config/discretisation"
grid = "solution/grid"
fluid = "solution/fluid"
