name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install BLAS
      run: |
        apt update
        apt install -y libopenblas-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
